import type { Metadata } from 'next';
import './globals.css';
import { inter } from '@/libs/fonts';

export const metadata: Metadata = {
	title: 'Schedulify - Trang chủ',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} antialiased`}>{children}</body>
		</html>
	);
}
