import { inter } from '@/utils/fonts';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Schedulify | Liên hệ',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} antialiased w-screen h-screen`}>
				{children}
			</body>
		</html>
	);
}
